services:
  misis-sigma:
    container_name: misis-sigma
    build: ./
    restart: always
    env_file:
      - path: ./.env
        required: false
      - path: ./.env.development.local
        required: false
    environment:
      - PORT=8000
    volumes:
      - ./data:/usr/src/app/data:rw
      #- ./media:/usr/src/app/media:rw